In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
vendas = pd.read_csv('vendas.csv')
df_clientes = pd.read_csv('clientes.csv')   
df_produtos = pd.read_csv('produtos.csv')
df_campanhas = pd.read_csv('campanhas.csv')
df_avaliacoes = pd.read_csv('avaliacoes.csv')
df_atendimentos = pd.read_csv('atendimentos.csv')
vendas1 = pd.read_csv('venda 1.csv')
vendas2 = pd.read_csv('venda 2.csv' )
vendas3 = pd.read_csv('venda 3.csv' )

In [ ]:
df_vendas = pd.concat([vendas, vendas1, vendas2, vendas3], ignore_index=True)

In [ ]:
df_clientes

,ID_Cliente,Nome,Idade,Sexo,Cidade,Estado,Canal_Aquisicao
0,1,Cauã Guerra,56,M,São Paulo,RS,Loja Física
1,2,Luísa Vargas,69,M,Rio de Janeiro,RJ,Online
2,3,Larissa Monteiro,46,M,Porto Alegre,PR,Online
3,4,Larissa Ribeiro,32,F,Porto Alegre,PR,Loja Física
4,5,Otávio Castro,60,M,Belo Horizonte,RJ,Online
...,...,...,...,...,...,...,...
995,996,Yuri Pinto,60,F,Curitiba,PR,Loja Física
996,997,Srta. Anna Liz Mendonça,64,M,São Paulo,SP,Online
997,998,Liz da Cunha,62,F,Curitiba,PR,Loja Física
998,999,Maria Cecília Vasconcelos,35,M,Porto Alegre,MG,Online
999,1000,Kamilly Teixeira,55,M,Belo Horizonte,RS,Online

In [ ]:
df_clientes.columns = df_clientes.columns.str.strip().str.lower()
df_vendas.columns = df_vendas.columns.str.strip().str.lower()
df_produtos.columns = df_produtos.columns.str.strip().str.lower()

In [ ]:
clientes_vendas = pd.merge(df_vendas, df_clientes, on="id_cliente", how="left")
tabela_final = pd.merge(clientes_vendas, df_produtos, on="id_produto", how="left")

In [ ]:
tabela_final

,id_venda,id_cliente,id_produto,data,quantidade,canal,valor_total,nome,idade,sexo,cidade,estado,canal_aquisicao,nome_produto,categoria,preco,marca
0,1,350,45,2022-09-23,4,Online,5795.64,Davi Luiz Peixoto,39,F,Rio de Janeiro,MG,Loja Física,Fritadeira Airfryer Mondial,Móveis,1448.91,Mondial
1,2,925,68,2024-02-09,1,Loja Física,4614.41,Murilo Cunha,28,M,Porto Alegre,PR,Online,Monitor LG Ultrawide,Eletrodomésticos,4614.41,LG
2,3,915,75,2022-09-11,4,Online,2057.48,Jade Freitas,30,M,Porto Alegre,RJ,Loja Física,Chromecast Google,Informática,514.37,Google
3,4,494,47,2024-05-10,4,Loja Física,12864.44,Kevin Casa Grande,51,F,Curitiba,PR,Loja Física,Máquina de Barbear Philips,Informática,3216.11,Philips
4,5,523,79,2023-10-15,4,Loja Física,13317.28,Asafe Mendonça,29,F,Porto Alegre,SP,Loja Física,Notebook Acer Aspire,Informática,3329.32,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23995,23195,99,68,2024-11-06 00:00:00,2,Online,922882.00,Ana Lívia Pereira,46,M,São Paulo,RS,Loja Física,Monitor LG Ultrawide,Eletrodomésticos,4614.41,LG
23996,23196,225,90,2024-10-14 00:00:00,2,Loja Física,653663.00,Ana Clara Cirino,54,F,Belo Horizonte,RJ,Online,Tablet Samsung Galaxy Tab,Móveis,3150.89,Samsung
23997,23197,974,15,2024-12-29 00:00:00,4,Loja Física,1256521.00,Yasmin Pimenta,66,F,São Paulo,PR,Online,"Monitor Samsung 24""",Eletrônicos,2946.66,Samsung
23998,23198,269,44,2025-06-13 00:00:00,3,Loja Física,983499.00,Ester Azevedo,37,M,Belo Horizonte,PR,Loja Física,Luminária LED,Eletrônicos,3278.33,NaN
23999,23199,54,23,2024-12-02 00:00:00,2,Online,929618.00,Davi Lucas Araújo,43,M,Belo Horizonte,MG,Online,Cooktop Brastemp,Eletrônicos,4648.09,Brastemp

In [ ]:
tabela_final['data'] = tabela_final['data'].astype(str).str.replace(' 00:00:00', '', regex=False)

In [ ]:
tabela_final.groupby("sexo")["valor_total"].sum().reset_index().sort_values(by="valor_total", ascending=False)

  sexo   valor_total
1    M  1.523881e+09
0    F  1.290266e+09

In [ ]:
tabela_final.loc[tabela_final['sexo'] == 'F']

,id_venda,id_cliente,id_produto,data,quantidade,canal,valor_total,nome,idade,sexo,cidade,estado,canal_aquisicao,nome_produto,categoria,preco,marca
0,1,350,45,2022-09-23,4,Online,5795.64,Davi Luiz Peixoto,39,F,Rio de Janeiro,MG,Loja Física,Fritadeira Airfryer Mondial,Móveis,1448.91,Mondial
3,4,494,47,2024-05-10,4,Loja Física,12864.44,Kevin Casa Grande,51,F,Curitiba,PR,Loja Física,Máquina de Barbear Philips,Informática,3216.11,Philips
4,5,523,79,2023-10-15,4,Loja Física,13317.28,Asafe Mendonça,29,F,Porto Alegre,SP,Loja Física,Notebook Acer Aspire,Informática,3329.32,NaN
5,6,98,30,2022-10-11,1,Loja Física,3282.59,Srta. Maya Aparecida,58,F,Porto Alegre,SP,Online,Relógio Garmin,Informática,3282.59,Garmin
9,10,570,34,2023-05-12,4,Online,1445.64,Beatriz Santos,57,F,São Paulo,PR,Online,Estabilizador APC,Eletrodomésticos,361.41,APC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23987,23187,44,91,2025-07-05,2,Loja Física,1083252.00,Ian Cassiano,24,F,Rio de Janeiro,PR,Online,"Monitor AOC 27""",Eletrodomésticos,4869.57,AOC
23988,23188,767,93,2025-07-22,4,Online,1873526.00,Gustavo Henrique Mendonça,55,F,Porto Alegre,RJ,Loja Física,Mouse Logitech MX Master,Informática,4252.20,Logitech
23991,23191,208,39,2025-07-29,3,Online,1500485.00,Mateus Peixoto,59,F,São Paulo,PR,Loja Física,Controle Remoto Universal,Informática,4714.29,NaN
23996,23196,225,90,2024-10-14,2,Loja Física,653663.00,Ana Clara Cirino,54,F,Belo Horizonte,RJ,Online,Tablet Samsung Galaxy Tab,Móveis,3150.89,Samsung
23997,23197,974,15,2024-12-29,4,Loja Física,1256521.00,Yasmin Pimenta,66,F,São Paulo,PR,Online,"Monitor Samsung 24""",Eletrônicos,2946.66,Samsung

In [ ]:
tabela_final.loc[tabela_final['sexo'] == 'M']

,id_venda,id_cliente,id_produto,data,quantidade,canal,valor_total,nome,idade,sexo,cidade,estado,canal_aquisicao,nome_produto,categoria,preco,marca
1,2,925,68,2024-02-09,1,Loja Física,4614.41,Murilo Cunha,28,M,Porto Alegre,PR,Online,Monitor LG Ultrawide,Eletrodomésticos,4614.41,LG
2,3,915,75,2022-09-11,4,Online,2057.48,Jade Freitas,30,M,Porto Alegre,RJ,Loja Física,Chromecast Google,Informática,514.37,Google
6,7,946,24,2024-02-24,4,Loja Física,18611.12,Bernardo Costela,39,M,Curitiba,PR,Loja Física,Forno Elétrico Philco,Móveis,4652.78,NaN
7,8,71,66,2024-03-07,2,Online,5811.56,Dr. Gael Henrique da Cunha,23,M,Rio de Janeiro,PR,Loja Física,Smartphone iPhone 13,Eletrônicos,2905.78,Apple
8,9,364,43,2023-06-18,2,Loja Física,70319.40,Leandro Brito,50,M,Belo Horizonte,RS,Loja Física,Extensão Elétrica,Eletrodomésticos,3515.97,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23993,23193,863,2,2025-06-07,1,Loja Física,342823.00,Raquel Pires,67,M,Rio de Janeiro,MG,Online,Smartphone Samsung Galaxy S21,Eletrodomésticos,3306.28,Samsung
23994,23194,617,96,2025-01-26,2,Online,85676.00,Aylla Montenegro,41,M,Belo Horizonte,RS,Loja Física,Smartwatch Huawei,Informática,428.38,Huawei
23995,23195,99,68,2024-11-06,2,Online,922882.00,Ana Lívia Pereira,46,M,São Paulo,RS,Loja Física,Monitor LG Ultrawide,Eletrodomésticos,4614.41,LG
23998,23198,269,44,2025-06-13,3,Loja Física,983499.00,Ester Azevedo,37,M,Belo Horizonte,PR,Loja Física,Luminária LED,Eletrônicos,3278.33,NaN
23999,23199,54,23,2024-12-02,2,Online,929618.00,Davi Lucas Araújo,43,M,Belo Horizonte,MG,Online,Cooktop Brastemp,Eletrônicos,4648.09,Brastemp

In [ ]:
'''q1 = np.percentile(tabela_final, 25)
q2 = np.percentile(tabela_final, 50)
q3 = np.percentile(tabela_final, 75)
mediana = np.median(tabela_final) # median = mediana

print(f'Primeiro quartil (Q1): {q1}')
print(f'Primeiro quartil (Q2): {q2}')
print(f'Primeiro quartil (Q3): {q3}')
print(f'Mediana {mediana}')'''

In [ ]:
tabela_final.groupby("nome_produto")["preco"].sum().reset_index().sort_values(by="preco", ascending=False)

                     nome_produto       preco
91               Teclado Logitech  1342623.43
46           Liquidificador Oster  1291495.73
44           Lava-Louças Brastemp  1279497.63
21  Câmera de Segurança Intelbras  1226870.00
49       Memória RAM Corsair 16GB  1226170.05
..                            ...         ...
76         Secador de Cabelo Gama    66230.84
42          Impressora HP Deskjet    66011.60
23                Echo Dot Amazon    57496.50
45            Leitor de Cartão SD    45351.54
87                      TV LG 50"    41083.27

[99 rows x 2 columns]

In [ ]:
tabela_produtos = tabela_final[['nome_produto', 'preco']].drop_duplicates().reset_index(drop=True)
tabela_produtos = tabela_produtos.dropna()
tabela_produtos

                     nome_produto    preco
0     Fritadeira Airfryer Mondial  1448.91
1            Monitor LG Ultrawide  4614.41
2               Chromecast Google   514.37
3      Máquina de Barbear Philips  3216.11
4            Notebook Acer Aspire  3329.32
..                            ...      ...
94  Smartphone Samsung Galaxy S21  3306.28
95                Ventilador Arno  3024.57
96           Mouse Gamer Redragon  3004.92
97                Echo Dot Amazon   255.54
98                  Controle Xbox  3917.60

[99 rows x 2 columns]

In [ ]:
tabela_produtos_array = np.array(tabela_produtos['preco'])

q1 = np.percentile(tabela_produtos_array, 25)
q2 = np.percentile(tabela_produtos_array, 50)
q3 = np.percentile(tabela_produtos_array, 75)
mediana = np.median(tabela_produtos_array) # median = median
media = np.mean(tabela_produtos_array) # mean = média

print(f'Primeiro quartil (Q1): {q1}')
print(f'Primeiro quartil (Q2): {q2}')
print(f'Primeiro quartil (Q3): {q3}')
print(f'Mediana {mediana}')
print(f'Média {media}')

Primeiro quartil (Q1): 1759.105
Primeiro quartil (Q2): 3087.52
Primeiro quartil (Q3): 4033.355
Mediana 3087.52
Média 2850.3936363636362

In [ ]:
contagem = tabela_final['nome_produto'].value_counts().reset_index()
contagem

                     nome_produto  count
0   Geladeira Brastemp Frost Free    276
1      Aspirador de Pó Electrolux    272
2          Pen Drive Sandisk 64GB    272
3               Kindle Paperwhite    272
4                Teclado Logitech    271
..                            ...    ...
94        Cadeira Gamer ThunderX3    214
95           Mouse Gamer Redragon    213
96           Volante Logitech G29    209
97              Smartwatch Xiaomi    204
98   Gabinete Gamer Cooler Master    201

[99 rows x 2 columns]

In [ ]:
count_array = np.array(contagem['count'])

q1 = np.percentile(count_array, 25)
q2 = np.percentile(count_array, 50)
q3 = np.percentile(count_array, 75)
mediana = np.median(count_array) # median = median
media = np.mean(count_array) # mean = média

distancia =  (media - mediana) / mediana
iqr = q3 - q1
limite_inferior = q1 - (1.5 * iqr)

print(f'Primeiro quartil (Q1): {q1}')
print(f'Primeiro quartil (Q2): {q2}')
print(f'Primeiro quartil (Q3): {q3}')
print(f'Mediana {mediana}')
print(f'Média {media}')
print(f'Limite Inferior: {limite_inferior}')
print(f'Distância: {distancia}')

Primeiro quartil (Q1): 232.5
Primeiro quartil (Q2): 241.0
Primeiro quartil (Q3): 254.0
Mediana 241.0
Média 241.97979797979798
Limite Inferior: 200.25
Distância: 0.0040655517833941045

In [ ]:
count_outliers = contagem[contagem['count'] < media]
count_outliers.tail()

                        nome_produto  count
48                Cooktop Electrolux    241
49                         TV LG 50"    241
50                 Smartwatch Huawei    240
51             Caixa de Som JBL Flip    240
52                Câmera Nikon D3500    240
53               Smart TV Samsung 4K    240
54          Impressora Epson Ecotank    240
55                    Projetor Epson    240
56         Mesa Digitalizadora Wacom    238
57     Secadora de Roupas Electrolux    238
58          Mouse Logitech MX Master    238
59            Notebook Dell Inspiron    237
60                 Tablet Apple iPad    237
61                  Drone DJI Mini 2    237
62              TV Philips Ambilight    236
63  Ar-condicionado LG Dual Inverter    236
64               Câmera GoPro Hero 9    235
65               Cafeteira Nespresso    235
66          Smartphone Motorola Edge    235
67         Máquina de Costura Singer    235
68         Chaleira Elétrica Mondial    234
69               Leitor de Cartão SD    234
70                   Ventilador Arno    234
71        Máquina de Barbear Philips    233
72             Forno Elétrico Philco    233
73                Ventilador Mondial    233
74              Grill George Foreman    232
75             Micro-ondas Panasonic    232
76              Fire TV Stick Amazon    231
77            Câmera Canon EOS Rebel    230
78              Smartphone iPhone 13    230
79                        Cabo USB-C    229
80                Fone de Ouvido JBL    229
81                   Filtro de Linha    228
82             Impressora HP Deskjet    227
83         Controle Remoto Universal    226
84                   Echo Dot Amazon    225
85            Micro-ondas Electrolux    225
86                     Controle Xbox    225
87           Notebook Lenovo Ideapad    224
88                    Placa-mãe ASUS    223
89       Fritadeira Airfryer Mondial    222
90              Máquina de Lavar 8kg    222
91         Tablet Samsung Galaxy Tab    222
92                 Extensão Elétrica    221
93                 Estabilizador APC    215
94           Cadeira Gamer ThunderX3    214
95              Mouse Gamer Redragon    213
96              Volante Logitech G29    209
97                 Smartwatch Xiaomi    204
98      Gabinete Gamer Cooler Master    201